name: pandas_workshop
channels:
    - conda-forge
dependencies:
    - python>=3.9.0,<=3.12.30
    - jupyterlab>=4.2.3
    - matplotlib=3.10.3
    - numpy=2.2.3
    - pandas=2.2.3
    - requests
    - seaborn=0.13.2
